### ISSUE TITLE
Fair use policy from Download box goes nowhere

### ISSUE THREAD

**Issue by pollardld** [Ecotrust/oceanadapt#39]
bug. will fix

**Comment by mpinsky** [comment]
This is still an issue as of today, see this link:

![image](https://user-images.githubusercontent.com/6370532/54249504-cf3d2a00-4516-11e9-8291-b9a333bec988.png)

**Comment by pollardld** [comment]
missed that one, sorry. should now be fixed. please feel free to reopen if not.
