### ISSUE TITLE
8. Download All processed data does not work now

### ISSUE THREAD

**Issue by pollardld** [Ecotrust/oceanadapt#55]

**Comment by pollardld** [comment]
Network error on download for all species only.

**Comment by mpinsky** [comment]
This issue is still a problem in the current website:

![image](https://user-images.githubusercontent.com/6370532/54248703-052cdf00-4514-11e9-8ed5-b450de642513.png)

**Comment by pollardld** [comment]
@mpinsky this should be fixed. Can you confirm?

**Comment by mpinsky** [comment]
Now works! Thanks. Closing #55.
