### ISSUE TITLE
28. Broken navigation from Fair Use policy to Data Download

### ISSUE THREAD

**Issue by pollardld** [Ecotrust/oceanadapt#59]

**Comment by mpinsky** [comment]
I checked today, and the issue still exists. Specifically, after opening the Data Download box, I clicked the Fair Use link. From the Fair Use page, I clicked the back arrow from the top-right of the page. The Data Download box again appeared, but it would no longer scroll down. I could, however, exit by clicking the "x" in the upper right.

**Comment by mpinsky** [comment]
In addition, the second Fair Use policy link leads nowhere:

![image](https://user-images.githubusercontent.com/6370532/54249416-82f1ea00-4516-11e9-8068-c34199383d85.png)
