### ISSUE TITLE
"Expand Options" link is not active when mouse pointer hovers above it

### ISSUE THREAD

**Issue by mpinsky** [Ecotrust/oceanadapt#73]
**Describe the bug**
When trying to choose a species, the "Expand Options" button/link is not active and does not respond when you click on it. It only activates and responds when the cursor is a couple inches to the left

**To Reproduce**
1. Go to any region
2. Try to click on "Expand Options"

**Expected behavior**
We expect the link to work when you click on it.

**Screenshots**
![image](https://user-images.githubusercontent.com/6370532/54544839-ca450400-4976-11e9-922f-50dd098d6262.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.3
 - Browser Chrome
 - Version 72.0.3626.121 (Official Build) (64-bit)

**Comment by pollardld** [comment]
Is this still an issue for you @mpinsky? 
If so and alright with you. it will be super helpful if perhaps you could demo this at tomorrow's meeting.

**Comment by mpinsky** [comment]
As of 8pm EDT, seems fixed.

**Comment by mpinsky** [comment]
This is still an issue on my 2560x1440 screen. Not an issue on 1440x900 laptop screen.

**Comment by mpinsky** [comment]
Tested on l2560x1440 screen, and now works.
