### ISSUE TITLE
Extra box on projections screen

### ISSUE THREAD

**Issue by mstuart1** [Ecotrust/oceanadapt#77]
**Describe the bug**
There is an extra box frame loading ahead of the projections maps.

**To Reproduce**
1. Go to Gulf of Alaska
2. Click on Atka mackerel species
3. Scroll down to View Projections and click
4. See a box frame before the 2 maps that load, preventing maps from loading side by side depending on screen size.

**Expected behavior**
2 maps load side by side without any empty frames on the screen

**Screenshots**
![Screen Shot 2019-03-19 at 1 11 48 PM](https://user-images.githubusercontent.com/29224545/54626937-9a663100-4a48-11e9-82de-cd43c04634a0.png)

**Desktop (please complete the following information):**
 - OS: MacOs 10.14.2
 - Browser Safari
 - Version 12.0.3

**Comment by mstuart1** [comment]
Also extra boxes are appearing in the historical map screen: 
![Screen Shot 2019-03-19 at 1 16 13 PM](https://user-images.githubusercontent.com/29224545/54627171-41e36380-4a49-11e9-8cf0-51b453b69cf7.png)

**Comment by mstuart1** [comment]
This appears to be an issue in Safari but not Chrome.

**Comment by mpinsky** [comment]
Now seems to work
