### ISSUE TITLE
Projections maps not showing up for all species

### ISSUE THREAD

**Issue by mstuart1** [Ecotrust/oceanadapt#80]
**Describe the bug**
For some species, projections maps appear as missing files.

**To Reproduce**
1. Go to Gulf of Alaska
2. Click on Actinaria spp. in the species selection area
3. Scroll down to View Projections and click
4. See error - 2 empty frame boxes.

**Expected behavior**
2 maps of projected locations.

**Screenshots**
![Screen Shot 2019-03-25 at 2 15 17 PM](https://user-images.githubusercontent.com/29224545/54944561-2a552080-4f0a-11e9-9f82-a6395b10c7f7.png)

**Desktop (please complete the following information):**
 - OS: Mac 10.14
 - Browser Safari 12.0.3, Chrome 73.0.3683.86, and Firefox 63.0.3 all showed the error

**Additional context**
If projections maps don't exist for all species, can there be a splash page that they are directed to or  point to the same "error" image (no projections maps exist for this species)?

**Comment by mpinsky** [comment]
No map shows up (like for Actiniaria in Gulf of Alaska) when no map exists. We need to handle this case elegantly.

**Comment by mstuart1** [comment]
This appears to be fixed.
